weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('about/',views.about,name='about'),
]

weather_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from weather import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='home'),
    path('weather/',include('weather.urls')),
]

weather/models.py
from django.db import models

# create your model here

weather/views.py
import requests
from django.shortcuts import render


def index(request):

    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=3725447341da2b87e5cecb32557320d4'

    city_weather = {}

    if request.method == 'GET':
        city = request.GET.get('cityname')

        r = requests.get(url.format(city)).json()

        city_weather = {
            'city' : city,
            'temperature' : r['main']['temp'],
            'description' : r['weather'][0]['description'],
            'icon' : r['weather'][0]['icon'],
        }

    return render(request, 'weather/index.html', {'city_weather' : city_weather})


def about(request):
    return render(request,'weather/about.html')

weather/templates/weather/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />

    <style>
        .abt{
            font-size: 17px;
            color: #808080;
            text-align: center;
            margin-top: 100px;
        }

        .custom-nav{
            height: 110px;
            background-color: #00cc99;
        }

        h2{
            color: white;
            padding: 33px;
            font-size: 30px;
            margin-left: 90px;
        }

        h3{
            text-align: right;
            margin-right: 70px;
            margin-top: -73px;
            font-size: 22px;
            color: white;
        }

        .custom-card {
            align-content: center;
            margin-top: 190px;
            margin-left: 470px;
        }

        .cust-footer{
            background-color: #e6e6e6;
            height: 110px;
            margin-top: 310px;
            padding: 47px;
            text-align: center;
        }
    </style>

</head>
<body>
    
    <!-- Navbar -->
    <nav class="custom-nav">
        <a href="{% url 'home' %}"><h2>WeatherApp</h2></a>
        <a href="{% url 'weather:about' %}"><h3>About</h3></a>
    </nav>

    <div class="abt">
        This app is created by Ishwar.
        TechStack - html, css, django.
    </div>

    <!-- Footer -->
    <footer class="cust-footer">
        Created by Ishwar
    </footer>

</body>
</html>

weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />

    <style>
        .custom-nav{
            height: 110px;
            background-color: #00cc99;
            
        }

        h2{
            color: white;
            padding: 33px;
            font-size: 30px;
            margin-left: 90px;
        }

        h3{
            text-align: right;
            margin-right: 70px;
            margin-top: -73px;
            font-size: 22px;
            color: white;
        }

        /* card */
        .custom-card {
       
            margin-top: 60px;
            margin-left: 550px;
        }

        .card {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            align-content: center;
            width: 30%;
        }
          
        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }
          
        .container {
            align-items: center;
            padding: 2px 16px;
        }

        .custom-form{
            margin-left: 520px;
            margin-top: 85px;
        }

        /* footer */
        .cust-footer{
            background-color: #e6e6e6;
            height: 110px;
            bottom : 0;
            margin-top : 148px;
            text-align: center;
            padding: 47px;
        }

        /* for input field */
        input[type=text], select {
            width: 35%;
            padding: 9px 20px;
            margin: -1px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
    </style>

</head>

<body>

    <!-- Navbar -->
    <nav class="custom-nav">
        <a href="{% url 'home' %}"><h2>WeatherApp</h2></a>
        <a href="{% url 'weather:about' %}"><h3>About</h3></a>
    </nav>

    <div class="custom-form">
        <form method="GET">
            {% csrf_token %}
            <input type="text" name="cityname" id="cityname" placeholder="Search City...">
            <button type="submit" class="button is-info">
                Search
            </button>        
        </form>
    </div>

    <div class="custom-card">
        <div class="card">
            <div class="container">
              <h4 style="font-size: 20px;"><b>{{ city_weather.city }}</b></h4> 
              <p>{{ city_weather.temperature }}° F</p> <br>
              <p style="font-size: 15px;">{{ city_weather.description }}</p>
            </div>
        </div>
    </div>

    <!-- footer -->
    <footer class="cust-footer">
        Created by Ishwar
    </footer>

</body>
</html>